### ISSUE TITLE
Order Service, Repository, 테스트 데이터 추가.

### ISSUE THREAD

**Issue by seung-woo-ryu** [seung-woo-ryu/kurly#2]
# ToDo
- [x] ApplicationRunner이용해서 디비 데이터 삽입.
- [x] OrderService 기능 추가.
- [x] 각 도메인별 Repsoitory 기능 추가.

**Comment by seung-woo-ryu** [comment]
ApplicationRunner를 이용해서 앱 시작할 때마다 데이터를 삽입하려고 함.
ddl-auto: create 일때는 앱이 종료되어도 데이터가 남아있는 문제가 발생해서 create-drop으로 변경

```
ddl-auto: create-drop
```
